### ISSUE TITLE
Couldn't load Connection String as SetConnectionString must have been forgotten

### ISSUE THREAD

**Issue by Orrouk** [2sic/eav-server#131]
05/09/2023 01:55:04
General Exception
AbsoluteURL DefaultDataProvider DotNetNuke.Data.SqlDataProvider DotNetNuke 
AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID: 68970d7b-b939-4ee1-8588-05f25d85b8b5
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:R+68c3Xv2R1IswJ8wldJccp5fOg=
Message:Search: Error #0 of 10 in 'DnnBusinessController' while indexing module 8048 on tab 1890, portal 0
StackTrace:
InnerMessage:Couldn't load Connection String as SetConnectionString must have been forgotten
InnerStackTrace:
  at ToSic.Eav.Configuration.DbConfiguration.get_ConnectionString() in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Configuration\DbConfiguration.cs:line 16
   at ToSic.Eav.Persistence.Efc.Models.EavDbContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in C:\Projects\2sxc\eav-server\ToSic.Eav.Persistence.Efc\Models\EavDbContext.cs:line 14
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Include[TEntity,TProperty](IQueryable`1 source, Expression`1 navigationPropertyPath)
   at ToSic.Eav.Repository.Efc.Parts.DbZone.AddMissingPrimaryApps()
   at ToSic.Eav.Repository.Efc.EfcRepositoryLoader.Zones() in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\EfcRepositoryLoader.cs:line 29
   at ToSic.Eav.Caching.AppsCacheBase.LoadZones(IAppLoaderTools sp) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Caching\Apps\AppsCacheBase.cs:line 36
   at ToSic.Eav.Caching.AppsCache.Zones(IAppLoaderTools tools) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Caching\Apps\AppsCache.cs:line 32
   at ToSic.Eav.Apps.AppStates.DefaultAppId(Int32 zoneId) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Apps\AppStates.cs:line 43
   at ToSic.Sxc.Dnn.Context.DnnModule.<>c__DisplayClass13_0.<GetInstanceAppIdAndName>b__0() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Context\DnnModule.cs:line 102
   at ToSic.Lib.Logging.ILog_Func.Func[TResult](ILog log, String parameters, Func`1 func, Boolean timer, Boolean enabled, String message, String cPath, String cName, Int32 cLine) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Logging\Log\ILog_Func.cs:line 135
   at ToSic.Sxc.Dnn.Context.DnnModule.GetInstanceAppIdAndName(Int32 zoneId) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Context\DnnModule.cs:line 0
   at ToSic.Sxc.Dnn.Context.DnnModule.get_BlockIdentifier() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Context\DnnModule.cs:line 77
   at ToSic.Sxc.Search.SearchController.<>c__DisplayClass10_0.<InitAllAndVerifyIfOk>b__0(ILogCall l) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Search\SearchController.cs:line 98
   at ToSic.Lib.Logging.ILog_Func.FuncLogResult[TResult](ILog log, Func`2 func, String parameters, String message, Boolean timer, CodeRef code, Boolean enabled, Boolean logResult) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Logging\Log\ILog_Func.cs:line 197
   at ToSic.Sxc.Search.SearchController.InitAllAndVerifyIfOk(IModule module) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Search\SearchController.cs:line 87
   at ToSic.Sxc.Search.SearchController.<>c__DisplayClass15_0.<GetModifiedSearchDocuments>b__0(ILogCall l) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Search\SearchController.cs:line 148
   at ToSic.Lib.Logging.ILog_Func.FuncLogResultMessage[TResult](ILog log, Func`2 func, String parameters, String message, Boolean timer, CodeRef code, Boolean enabled, Boolean logResult) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Logging\Log\ILog_Func.cs:line 246
   at ToSic.Sxc.Search.SearchController.GetModifiedSearchDocuments(IModule module, DateTime beginDate) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Search\SearchController.cs:line 144
   at ToSic.Sxc.Dnn.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\DnnBusinessController.cs:line 115
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by Orrouk** [comment]
I found that to repropagate the authorizations on folders and files solved the thing. We new:
 "Couldn't load Connection String as SetConnectionString must have been forgotten"... Now we understand why.
